# Generated by Django 2.2.4 on 2019-08-29 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('tissue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GeneExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_id', models.CharField(max_length=200)),
                ('tpm', models.FloatField(default=0)),
                ('sample_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneExp.SampleInf')),
            ],
        ),
    ]
