# Generated by Django 2.2.4 on 2019-08-29 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geneExp', '0002_gene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneexp',
            name='gene_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geneExp.Gene'),
        ),
    ]
